const COMMANDS = Object.freeze({
  GET_STATUS: 'GET_STATUS',
  LOGOUT: 'LOGOUT',
  START_VIDEO: 'START_VIDEO',
  STOP_VIDEO: 'STOP_VIDEO',
});

const MESSAGE_TYPES = Object.freeze({
  COMMAND: 'COMMAND',
  RESPONSE: 'RESPONSE',
  SESSION_ACTIVATE: 'SESSION_ACTIVATE',
  SESSION_REVOKE: 'SESSION_REVOKE',
  SESSION_SYNC: 'SESSION_SYNC',
});

const VIDEO_COMMANDS = new Set([
  COMMANDS.GET_STATUS,
  COMMANDS.START_VIDEO,
  COMMANDS.STOP_VIDEO,
]);
const CLIENT_COMMANDS = new Set([...VIDEO_COMMANDS, COMMANDS.LOGOUT]);
const SUPPORTED_COMMANDS = VIDEO_COMMANDS;

module.exports = {
  CLIENT_COMMANDS,
  COMMANDS,
  MESSAGE_TYPES,
  SUPPORTED_COMMANDS,
  VIDEO_COMMANDS,
};
